import type { AIModel } from "@/types";

export const AI_MODELS: AIModel[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    description: "OpenAI's flagship model with vision and fast reasoning.",
    contextWindow: 128000,
    inputPrice: 5.0,
    outputPrice: 15.0,
    capabilities: ["Vision", "Code", "Reasoning", "Tools"],
    badge: "Most Popular",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    description: "Affordable and intelligent for everyday tasks.",
    contextWindow: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: ["Code", "Reasoning", "Fast"],
    badge: "Fast",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "anthropic",
    description: "Anthropic's best model for coding and analysis.",
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: ["Code", "Analysis", "Writing", "Vision"],
    badge: "Best for Code",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "anthropic",
    description: "Powerful model for complex tasks.",
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: ["Reasoning", "Writing", "Analysis"],
  },
  {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "google",
    description: "Google's multimodal model with massive context.",
    contextWindow: 2000000,
    inputPrice: 1.25,
    outputPrice: 5.0,
    capabilities: ["Vision", "Audio", "Video", "Code"],
    badge: "2M Context",
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "google",
    description: "Fast and efficient model from Google.",
    contextWindow: 1000000,
    inputPrice: 0.075,
    outputPrice: 0.3,
    capabilities: ["Fast", "Vision", "Code"],
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "deepseek",
    description: "High-performance open model with strong reasoning.",
    contextWindow: 64000,
    inputPrice: 0.27,
    outputPrice: 1.1,
    capabilities: ["Code", "Reasoning", "Math"],
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "qwen",
    description: "Alibaba's top model for multilingual tasks.",
    contextWindow: 32768,
    inputPrice: 2.8,
    outputPrice: 8.4,
    capabilities: ["Multilingual", "Code", "Reasoning"],
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B",
    provider: "llama",
    description: "Meta's open-source model at scale.",
    contextWindow: 128000,
    inputPrice: 0.9,
    outputPrice: 0.9,
    capabilities: ["Code", "Reasoning", "Open Source"],
    badge: "Open Source",
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "mistral",
    description: "Mistral's flagship model for enterprise.",
    contextWindow: 32000,
    inputPrice: 2.0,
    outputPrice: 6.0,
    capabilities: ["Code", "Reasoning", "Multilingual"],
  },
  {
    id: "openrouter/auto",
    name: "OpenRouter Auto",
    provider: "openrouter",
    description: "Automatically routes to the best model.",
    contextWindow: 128000,
    inputPrice: 1.0,
    outputPrice: 1.0,
    capabilities: ["Auto-routing", "Multi-model"],
    badge: "Smart Routing",
  },
  {
    id: "agentrouter/auto",
    name: "AgentRouter Auto",
    provider: "agentrouter",
    description: "Intelligent routing for agent workflows.",
    contextWindow: 128000,
    inputPrice: 0.8,
    outputPrice: 0.8,
    capabilities: ["Agent Routing", "Multi-model"],
  },
];

export function getModelById(id: string): AIModel | undefined {
  return AI_MODELS.find((m) => m.id === id);
}

export function getModelsByProvider(provider: string): AIModel[] {
  return AI_MODELS.filter((m) => m.provider === provider);
}
